Split workflow into different steps
Signed-off-by: Misha Behersky <bmwant@gmail.com>

diff --git a/.github/workflows/e2e-compose-tests.yml b/.github/workflows/e2e-compose-tests.yml
--- a/.github/workflows/e2e-compose-tests.yml
+++ b/.github/workflows/e2e-compose-tests.yml
@@ -20,70 +20,73 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Configure services
+        run: |
+          echo "BASEDIR=$(git rev-parse --show-toplevel)" >> $GITHUB_ENV
+          echo "VERSION=$(git rev-parse --short=12 HEAD)" >> $GITHUB_ENV
+
+          # Deploy all services: istio, curiefense, and echoserver (test app)
+          deploy/deploy-ci-compose.sh
+
+      - name: Install dependencies
+        run: |
+          echo "-- Install curieconfctl --"
+
+          python3 -m venv "${{ env.BASEDIR }}/venv"
+          source "${{ env.BASEDIR }}/venv/bin/activate"
+          pip install --no-cache-dir -r "${{ env.BASEDIR }}/e2e/requirements.txt"
+
+          pushd "curiefense/curieconf/utils"
+            pip install -e .
+          popd
+
+          pushd "curiefense/curieconf/client"
+            pip install -e .
+          popd
+
       - name: Run tests
         run: |
-            export BASEDIR=$(git rev-parse --show-toplevel)
-            export VERSION=$(git rev-parse --short=12 HEAD)
+          echo "-- Run e2e tests --"
+          IP=127.0.0.1
+          NGINX_ENDPOINT="http://$IP:31081"
+          ENVOY_ENDPOINT="http://$IP:30081"
+          LUATESTS_PATH="${{ env.BASEDIR }}/curiefense/curieproxy/rust/luatests"
 
-            # Deploy all services: istio, curiefense, and echoserver (test app)
-            deploy/deploy-ci-compose.sh
+          pushd e2e
+          echo "-- Running e2e tests for nginx proxy --"
+          pytest --log-level INFO \
+            --base-protected-url $NGINX_ENDPOINT \
+            --base-conf-url http://$IP:30000/api/v3/ \
+            --base-ui-url http://$IP:30080 \
+            --elasticsearch-url http://$IP:9200/ \
+            --luatests-path $LUATESTS_PATH \
+            --junit-xml pytest.xml .
+          popd
 
-            echo "-- Install curieconfctl --"
-
-            python3 -m venv "$BASEDIR/venv"
-            source "$BASEDIR/venv/bin/activate"
-            pip install --no-cache-dir -r "$BASEDIR/e2e/requirements.txt"
-
-            pushd "curiefense/curieconf/utils"
-            pip install -e .
-            popd
-
-            pushd "curiefense/curieconf/client"
-            pip install -e .
-            popd
-
-            echo "-- Run e2e tests --"
-            IP=127.0.0.1
-            NGINX_ENDPOINT="http://$IP:31081"
-            ENVOY_ENDPOINT="http://$IP:30081"
-            LUATESTS_PATH="$BASEDIR/curiefense/curieproxy/rust/luatests"
-
-            pushd e2e
-            echo "-- Running e2e tests for nginx proxy --"
-            pytest --log-level INFO \
-              --base-protected-url $NGINX_ENDPOINT \
-              --base-conf-url http://$IP:30000/api/v3/ \
-              --base-ui-url http://$IP:30080 \
-              --elasticsearch-url http://$IP:9200/ \
-              --luatests-path $LUATESTS_PATH \
-              --junit-xml pytest.xml .
-            popd
-
-            echo "-- Run bitflip tests tests --"
-            echo "TODO"
-            # Here we are not interested in the e2e tests results, almost all
-            # of which are expected to fail. We just want to ensure envoy does
-            # not crash with malformed requests.
-            # A subset of tests is selected to exercise most code paths; not
-            # all tests are run to avoid spending more than 5 minutes on this
-            # in CI
-            pushd e2e
-            echo "bit flip tests"
-            ENVOY_PID_BEFORE=$(pgrep envoy)
-            pytest --log-level INFO \
-              --base-protected-url $ENVOY_ENDPOINT \
-              --base-conf-url http://$IP:30000/api/v3/ \
-              --base-ui-url http://$IP:30080 \
-              --elasticsearch-url http://$IP:9200/ \
-              --luatests-path $LUATESTS_PATH \
-              --flip-requests . || true
-            ENVOY_PID_AFTER=$(pgrep envoy)
-            if [ "$ENVOY_PID_BEFORE" != "$ENVOY_PID_AFTER" ]; then
-              echo "Error: probable envoy crash during bitflip smoke testing"
-              exit 1
-            fi
-            popd
-
+          echo "-- Run bitflip tests tests --"
+          echo "TODO"
+          # Here we are not interested in the e2e tests results, almost all
+          # of which are expected to fail. We just want to ensure envoy does
+          # not crash with malformed requests.
+          # A subset of tests is selected to exercise most code paths; not
+          # all tests are run to avoid spending more than 5 minutes on this
+          # in CI
+          pushd e2e
+          echo "bit flip tests"
+          ENVOY_PID_BEFORE=$(pgrep envoy)
+          pytest --log-level INFO \
+            --base-protected-url $ENVOY_ENDPOINT \
+            --base-conf-url http://$IP:30000/api/v3/ \
+            --base-ui-url http://$IP:30080 \
+            --elasticsearch-url http://$IP:9200/ \
+            --luatests-path $LUATESTS_PATH \
+            --flip-requests . || true
+          ENVOY_PID_AFTER=$(pgrep envoy)
+          if [ "$ENVOY_PID_BEFORE" != "$ENVOY_PID_AFTER" ]; then
+            echo "Error: probable envoy crash during bitflip smoke testing"
+            exit 1
+          fi
+          popd
 
       - name: Dump compose logs
         if: ${{ failure() }}
